### ISSUE TITLE
Keine Suchresultate

### ISSUE THREAD

**Issue by akroii** [feedbackmedia/contao-cearch-pro#5]
Ich bekomme keine Suchresultate wenn ich die Suche ausführe.
Suche ist aktiviert. Suchindex wurde aufgebaut. 

Das Suchtemplate (zCearchPro -> mod_search) habe ich nicht modifiziert.
Selbst beim Contao eigenen  mod_search bekomme ich bei ```$this->results``` mit var_dump() nur ```string(0) ""```

Cearch Pro 	1.0.1   6
Contao 3.4.4

**Comment by akroii** [comment]
Der Fehler trat nach dem Update auf die oben genannte Version auf.

**Comment by smohring** [comment]
Hi akorii,

Kann ich leider nicht nachvollziehen, bitte nochmals die neuste Version hier aus GIT installieren (eventuell hast Du noch die alte 1.0.1).
Dann Datenbank Update und Suchindex neu erstellen lassen.

Wenns dann immernoch nicht geht, bitte nochmal bescheid geben.
