### ISSUE TITLE
Kompatibilität Contao 3.5(.3)

### ISSUE THREAD

**Issue by Wagnerwagner** [feedbackmedia/contao-cearch-pro#6]
Hallo,
hätte die Erweiterung gerne in Contao 3.5.3 eingesetzt.
Leider lässt sie sich über den Composer gar nicht erst installieren, da die Kompatibilität auf <=3.5 gesetzt ist.
Wird es in naher Zukunft ein Update geben bzw. werden die Kompatibilitätsangaben angepasst?

**Comment by smohring** [comment]
Ich werde demnächst ein Update veröffentlichen, kompatibel ist die Version auf jedenfall - lediglich die composer.json müsste angepasst werden...

**Comment by MacKP** [comment]
Sieht so aus, als ob die Version auch mit Contao 3.5.6 läuft. Wäre super, wenn du eine neue composer.json erstellen würdest ;-)

Viele Grüße

**Comment by smohring** [comment]
Merge request übernommen, wenn jemand Zeit hat, bitte auch mal testen obs mit 4.x auch geht :) Kann mir gut vorstellen, dass das geht.

**Comment by MacKP** [comment]
Danke!
