### ISSUE TITLE
Doppelte Url in tl_search

### ISSUE THREAD

**Issue by basistom** [feedbackmedia/contao-cearch-pro#8]
Sobald zCearchPro installiert ist wird der Suchindex mit falschen URLs im Format

http://www.domain.de/http://www.domain.de/…

erzeugt.

**Comment by erikherbert** [comment]
Will this fixed? Do you need help?

**Comment by smohring** [comment]
Sorry für die späte Antwort - sollte jetzt funktionieren. Das Problem ist bei meinen kurzen tests nicht mehr aufgetreten und trat auch nur auf wenn ein Domainname im Pageroot hinterlegt war.
