### ISSUE TITLE
Verwendung von \String:: führt zu Fehlern bei PHP 7

### ISSUE THREAD

**Issue by mp-itconsulting** [feedbackmedia/contao-cearch-pro#9]
In classes/Search.php und moules/ModuleSearch.php muss \String:: in \StringUtil:: umbenannt werden da "String" nicht mehr als Class name verwendet werden darf.

Fehlermeldung:
... PHP Fatal error:  Cannot use 'String' as class name as it is reserved ...

Gruß
M.P.

**Comment by BugBuster1701** [comment]
Die Freigabe muss dann aber auch für Contao angehoben werden, denn StrungUtil gibt es erst ab 3.5.5.

**Comment by bytehead** [comment]
`StringUtil` gibts bereits ab [Contao 3.5.1](https://github.com/contao/core/blob/3.5.1/system/modules/core/library/Contao/StringUtil.php).

**Comment by BugBuster1701** [comment]
Ja, hast recht, geben tut es die ab 3.5.1.
Weiß nicht mehr wie ich auf 3.5.5 gekommen bin bei einer meiner Erweiterungen, habe jetzt nur gefunden, dass es einen Fix gab in 3.5.4 den ich brauchte.
Mit version_compare arbeiten wie in deinem PR ist natürlich auch eine Variante.

**Comment by bytehead** [comment]
Normalerweise würde ich auch in der `composer.json` das Requirement für Contao erhöhen, wenn es zuviele `version_compare`-Aufrufe gibt.

**Comment by smohring** [comment]
Bin über das ganze nochmal drüber. Sollte aber passen - ich mach das hier damit mal zu.
